In [39]:
#dependencies
import pandas as pd

In [40]:
#reading in the csv of the state abbreviations
states_path = 'statesUSAbbrevs.csv'
states_abbrev_df = pd.read_csv(states_path)
states_abbrev_df.head()

   state_name state_abbrev
0     Alabama        US-AL
1      Alaska        US-AK
2     Arizona        US-AZ
3    Arkansas        US-AR
4  California        US-CA

In [41]:
#reading in all the category csvs
path = 'google_trends_csvs/Arts & Entertainment_states.csv'
arts_entertainment_df = pd.read_csv(path)
arts_entertainment_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,80,80,98,96,98,97,93,95,91,...,93,83,91,98,93,97,99,91,96,92
1,2019-01-13,80,90,95,97,96,93,87,88,90,...,93,82,92,93,87,96,95,94,92,95
2,2019-01-20,75,79,95,94,88,93,88,82,89,...,91,79,91,92,89,96,93,90,85,89
3,2019-01-27,74,81,93,91,93,90,85,84,90,...,88,75,90,92,88,92,92,89,93,86
4,2019-02-03,76,82,95,92,89,92,87,86,93,...,93,77,91,93,88,90,93,89,93,93

In [42]:
path = 'google_trends_csvs/Autos & Vehicles_states.csv'
autos_vehicles_df = pd.read_csv(path)
autos_vehicles_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,71,73,75,73,82,66,78,65,79,...,62,68,73,64,69,77,70,76,66,63
1,2019-01-13,73,72,78,74,81,68,81,69,76,...,67,69,74,63,73,80,72,76,64,67
2,2019-01-20,73,68,77,71,78,66,75,73,72,...,65,68,71,62,68,77,69,71,61,67
3,2019-01-27,72,68,77,76,78,67,74,68,86,...,65,68,72,61,72,78,70,71,67,63
4,2019-02-03,74,65,76,77,79,70,80,77,84,...,60,70,73,64,74,76,72,76,64,68

In [43]:
path = 'google_trends_csvs/Beauty & Fitness_states.csv'
beauty_fitness_df = pd.read_csv(path)
beauty_fitness_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,76,79,89,88,95,97,87,78,95,...,89,83,87,96,100,98,91,93,100,95
1,2019-01-13,78,81,86,89,89,96,82,78,91,...,91,83,83,96,86,97,90,96,95,95
2,2019-01-20,73,85,83,86,90,94,84,75,87,...,90,78,84,89,82,95,86,86,80,90
3,2019-01-27,73,87,84,88,89,91,80,78,94,...,87,75,83,91,81,92,86,85,76,91
4,2019-02-03,77,77,86,88,88,91,81,76,92,...,90,76,88,91,80,92,79,82,80,83

In [44]:
path = 'google_trends_csvs/Books & Literature_states.csv'
books_lit_df = pd.read_csv(path)
books_lit_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,73,90,77,82,80,82,85,74,70,...,95,84,76,94,89,83,83,85,89,83
1,2019-01-13,82,76,88,87,82,89,84,66,71,...,85,90,84,86,92,88,91,89,87,77
2,2019-01-20,82,85,82,81,79,83,75,67,75,...,88,89,82,86,81,82,87,89,76,80
3,2019-01-27,79,76,83,88,82,90,79,65,76,...,91,84,82,87,88,78,77,80,71,72
4,2019-02-03,84,95,87,88,81,86,76,68,78,...,77,90,84,81,86,78,74,92,82,74

In [45]:
path = 'google_trends_csvs/top_trends/Action & Adventure Films_states.csv'
action_adventure_df = pd.read_csv(path)
action_adventure_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,60,49,64,74,70,77,64,61,70,...,90,62,72,57,58,72,69,86,69,72
1,2019-01-13,72,56,75,64,72,70,70,80,82,...,78,71,77,71,62,83,73,66,73,44
2,2019-01-20,67,74,66,69,67,70,61,61,64,...,70,75,73,72,62,78,72,78,70,54
3,2019-01-27,68,48,67,58,65,66,59,60,77,...,100,62,70,53,42,71,69,62,66,60
4,2019-02-03,58,69,63,66,61,68,56,71,63,...,69,63,70,70,47,61,72,71,66,39

In [46]:
path = 'google_trends_csvs/top_trends/Campaigns & Elections_states.csv'
elections_df = pd.read_csv(path)
elections_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
1,2019-01-13,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
2,2019-01-20,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
3,2019-01-27,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,1,0,0,0,0
4,2019-02-03,0,0,0,0,0,0,0,0,3,...,0,0,0,0,1,1,0,0,0,0

In [47]:
path = 'google_trends_csvs/top_trends/Celebrities & Entertainment News_states.csv'
celebs_df = pd.read_csv(path)
celebs_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,67,72,67,70,71,68,69,62,96,...,74,69,71,57,64,72,69,56,74,78
1,2019-01-13,67,65,63,65,66,64,71,65,83,...,63,70,65,58,61,71,64,69,72,65
2,2019-01-20,57,61,58,70,58,57,65,51,81,...,53,64,61,57,67,68,60,59,62,80
3,2019-01-27,60,59,60,72,63,64,62,63,93,...,78,66,64,64,49,66,60,65,72,65
4,2019-02-03,64,64,60,64,60,55,59,47,85,...,54,61,63,58,42,59,63,60,65,77

In [48]:
path = 'google_trends_csvs/top_trends/Discrimination & Identity Relations_states.csv'
discrim_df = pd.read_csv(path)
discrim_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,16,10,22,15,24,11,17,25,66,...,37,17,21,20,14,25,20,27,20,9
1,2019-01-13,14,29,27,24,27,24,23,33,40,...,82,20,23,29,14,28,27,12,23,0
2,2019-01-20,11,29,30,27,29,20,24,12,42,...,36,20,22,32,27,30,24,24,22,0
3,2019-01-27,18,39,24,14,32,25,25,28,42,...,27,21,26,32,21,31,25,15,24,0
4,2019-02-03,17,9,30,22,25,28,27,28,55,...,18,20,28,27,41,24,26,15,26,25

In [49]:
path = 'google_trends_csvs/top_trends/Entertainment Media_states.csv'
entertainment_media_df = pd.read_csv(path)
entertainment_media_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,90,81,88,83,86,87,69,57,88,...,73,74,81,85,59,86,88,73,74,56
1,2019-01-13,89,88,78,71,78,86,72,55,100,...,49,77,79,78,84,88,84,84,79,68
2,2019-01-20,94,66,72,79,74,73,73,69,73,...,59,77,77,76,55,80,84,92,86,94
3,2019-01-27,93,69,74,65,70,79,66,83,73,...,53,66,78,81,43,76,73,65,78,55
4,2019-02-03,78,44,65,58,67,69,55,67,78,...,50,65,72,72,59,63,80,60,74,66

In [50]:
path = 'google_trends_csvs/top_trends/Game Systems & Consoles_states.csv'
games_consoles_df = pd.read_csv(path)
games_consoles_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,54,64,53,59,58,61,47,62,74,...,59,61,61,61,46,53,67,42,49,69
1,2019-01-13,59,67,48,70,57,57,49,39,69,...,39,55,55,53,65,51,56,56,50,31
2,2019-01-20,52,47,46,60,54,61,47,54,53,...,51,52,54,57,51,50,55,53,51,33
3,2019-01-27,55,72,49,61,58,66,50,46,61,...,48,61,59,66,77,52,62,48,62,62
4,2019-02-03,49,54,46,61,53,59,38,41,46,...,40,51,58,49,39,47,61,49,53,39

In [51]:
path = 'google_trends_csvs/top_trends/Health News_states.csv'
health_news_df = pd.read_csv(path)
health_news_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,37,27,90,58,67,77,63,40,79,...,55,47,64,82,49,45,50,35,33,40
1,2019-01-13,39,27,54,33,62,54,60,31,56,...,11,42,69,45,49,55,46,27,50,0
2,2019-01-20,26,13,100,28,59,59,64,23,44,...,32,51,63,60,0,51,65,75,53,59
3,2019-01-27,52,39,50,51,64,79,55,47,50,...,43,42,73,53,64,58,50,68,40,79
4,2019-02-03,51,26,43,28,57,70,59,23,93,...,32,49,71,76,32,67,61,20,56,19

In [52]:
path = 'google_trends_csvs/top_trends/Infectious Diseases_states.csv'
inf_diseases_df = pd.read_csv(path)
inf_diseases_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,11,8,8,16,10,8,11,14,12,...,9,12,11,11,10,9,10,10,7,11
1,2019-01-13,10,14,8,11,9,9,12,7,10,...,11,10,11,12,7,9,11,11,7,9
2,2019-01-20,10,12,8,12,9,8,9,8,11,...,11,11,11,10,9,9,14,11,7,7
3,2019-01-27,13,14,9,14,10,9,12,12,11,...,11,12,14,14,9,10,20,11,7,12
4,2019-02-03,14,12,9,14,11,9,11,12,15,...,16,13,15,13,9,10,13,14,7,11

In [53]:
path = 'google_trends_csvs/top_trends/Law Enforcement_states.csv'
law_enf_df = pd.read_csv(path)
law_enf_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,54,61,44,73,41,53,51,77,61,...,70,65,55,66,59,46,40,52,54,35
1,2019-01-13,63,83,51,63,39,48,37,46,64,...,49,65,57,62,39,56,40,59,47,49
2,2019-01-20,53,51,41,69,36,48,49,36,51,...,62,52,49,42,41,45,37,67,46,52
3,2019-01-27,56,43,47,71,41,50,49,37,60,...,52,65,55,47,84,47,37,48,58,75
4,2019-02-03,53,72,34,70,34,48,41,38,60,...,49,60,52,52,41,41,39,53,67,30

In [54]:
path = 'google_trends_csvs/top_trends/Lottery & Sweepstakes_states.csv'
lotto_df = pd.read_csv(path)
lotto_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,52,23,48,50,50,39,54,60,73,...,51,55,53,63,54,89,49,52,40,70
1,2019-01-13,45,53,46,39,45,38,48,61,76,...,51,56,53,52,41,84,40,40,41,60
2,2019-01-20,49,23,41,46,43,35,45,55,58,...,52,56,53,43,55,92,41,45,33,76
3,2019-01-27,44,76,48,57,48,37,57,45,79,...,32,55,52,49,60,95,47,44,33,34
4,2019-02-03,48,69,48,56,48,32,50,45,74,...,41,54,55,49,42,81,39,44,33,68

In [55]:
path = 'google_trends_csvs/top_trends/Mobile Phones_states.csv'
mobiles_df = pd.read_csv(path)
mobiles_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,67,66,61,71,53,59,62,51,60,...,60,62,56,58,68,61,59,75,64,39
1,2019-01-13,68,81,57,66,52,63,58,65,49,...,78,66,58,60,44,55,61,66,65,46
2,2019-01-20,64,59,58,62,50,62,61,50,55,...,54,65,55,58,63,54,58,55,59,47
3,2019-01-27,61,65,58,63,52,62,54,65,58,...,72,65,54,51,63,56,56,77,57,44
4,2019-02-03,56,50,54,61,49,59,55,63,58,...,57,63,54,49,60,54,53,68,60,41

In [56]:
path = 'google_trends_csvs/top_trends/Online Video_states.csv'
online_vids_df = pd.read_csv(path)
online_vids_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,92,80,77,84,84,88,79,81,78,...,86,94,77,85,91,88,76,82,91,82
1,2019-01-13,84,98,81,88,86,90,91,92,82,...,100,88,79,84,88,93,77,93,80,83
2,2019-01-20,91,82,82,85,83,85,80,100,72,...,83,86,75,74,71,89,73,88,82,84
3,2019-01-27,79,75,78,78,82,87,85,68,83,...,74,91,78,75,95,90,77,85,83,70
4,2019-02-03,82,93,75,90,81,88,80,82,73,...,75,86,79,73,85,81,74,91,83,88

In [57]:
path = 'google_trends_csvs/top_trends/Science Fiction & Fantasy_states.csv'
scifi_fantasy_df = pd.read_csv(path)
scifi_fantasy_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,93,61,46,63,56,46,59,38,60,...,41,45,58,47,39,48,59,31,56,81
1,2019-01-13,53,30,43,51,56,41,50,40,48,...,56,44,50,44,47,50,44,53,64,46
2,2019-01-20,76,30,36,54,54,53,59,49,59,...,40,46,50,39,47,49,50,42,52,40
3,2019-01-27,49,45,38,66,55,48,56,37,51,...,71,44,50,35,42,52,43,45,68,23
4,2019-02-03,47,33,36,48,51,43,50,27,44,...,70,40,53,47,47,53,40,35,54,45

In [58]:
path = 'google_trends_csvs/top_trends/Sports News_states.csv'
sport_news_df = pd.read_csv(path)
sport_news_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,59,54,69,56,87,76,54,79,48,...,70,59,81,65,48,86,69,62,54,26
1,2019-01-13,58,66,61,69,74,60,68,47,81,...,48,65,75,66,77,72,72,53,55,32
2,2019-01-20,51,18,58,52,71,65,52,36,43,...,34,62,77,55,52,69,54,49,50,50
3,2019-01-27,53,48,54,56,74,58,74,44,53,...,26,47,66,54,35,70,65,36,49,25
4,2019-02-03,82,53,59,73,73,65,62,38,40,...,72,86,90,73,29,79,67,82,52,50

In [59]:
path = 'google_trends_csvs/top_trends/TV Shows & Programs_states.csv'
tv_shows_df = pd.read_csv(path)
tv_shows_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,81,76,90,80,92,88,89,85,82,...,77,88,84,91,96,95,90,93,91,72
1,2019-01-13,84,78,88,88,88,83,83,80,85,...,74,88,83,88,76,89,85,88,85,94
2,2019-01-20,78,78,84,79,87,88,84,74,90,...,70,87,84,85,90,89,90,86,83,82
3,2019-01-27,80,72,85,78,85,81,83,73,89,...,74,83,79,81,89,86,82,87,83,85
4,2019-02-03,82,69,85,79,85,83,79,75,80,...,77,84,86,86,96,89,90,83,81,95

In [60]:
path = 'google_trends_csvs/top_trends/Voice & Video Chat_states.csv'
vv_chat_df = pd.read_csv(path)
vv_chat_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,45,42,61,52,64,47,44,47,23,...,10,51,64,26,8,51,62,50,27,0
1,2019-01-13,44,56,45,52,59,55,38,15,56,...,29,51,59,26,32,52,55,47,42,36
2,2019-01-20,50,68,73,65,51,51,30,30,45,...,48,68,57,31,24,42,34,46,36,12
3,2019-01-27,46,69,73,66,67,87,47,100,74,...,57,51,68,57,48,55,46,47,44,0
4,2019-02-03,48,27,47,87,62,73,48,38,52,...,58,45,67,53,24,56,69,38,35,36

In [61]:
path = 'google_trends_csvs/top_trends/Weather_states.csv'
weather_df = pd.read_csv(path)
weather_df.head()

,time,US-AL,US-AK,US-AZ,US-AR,US-CA,US-CO,US-CT,US-DE,US-DC,...,US-SD,US-TN,US-TX,US-UT,US-VT,US-VA,US-WA,US-WV,US-WI,US-WY
0,2019-01-06,48,97,45,63,66,56,51,70,68,...,30,54,59,57,73,91,27,66,34,47
1,2019-01-13,66,75,52,81,82,48,100,95,90,...,57,64,73,66,91,100,25,88,41,56
2,2019-01-20,72,68,34,75,37,67,76,65,50,...,56,77,73,58,100,65,22,74,73,65
3,2019-01-27,100,68,42,68,75,55,87,100,100,...,76,100,74,53,83,93,31,100,100,54
4,2019-02-03,54,74,57,80,88,71,50,52,61,...,63,68,77,91,67,60,100,56,59,78

In [62]:
#creating a dictionary of all the cat dfs
combo_cats_dict = {
    'arts_entertainment': arts_entertainment_df,
    'autos': autos_vehicles_df,
    'beauty_fitness': beauty_fitness_df,
    'books_lit': books_lit_df,
    'action_adventure': action_adventure_df,
    'campaigns_elections': elections_df,
    'celebs': celebs_df,
    'discrimination': discrim_df,
    'entertainment_media': entertainment_media_df,
    'games_systems_consoles': games_consoles_df,
    'health_news': health_news_df,
    'infectious_diseases': inf_diseases_df,
    'law_enf': law_enf_df,
    'lottos': lotto_df,
    'mobiles': mobiles_df,
    'online_vids': online_vids_df,
    'scifi_fantasy': scifi_fantasy_df,
    'sport_news': sport_news_df,
    'tv_shows': tv_shows_df,
    'voice_vid_chat': vv_chat_df,
    'weather': weather_df
}

In [63]:
#list for appending category names to
cats_names_list = []

In [64]:
#printing each csv's dict key, appending each to list for columns
for key, value in combo_cats_dict.items():
    print(key)
    #appending cat names to list
    cats_names_list.append(key)

arts_entertainment
autos
beauty_fitness
books_lit
action_adventure
campaigns_elections
celebs
discrimination
entertainment_media
games_systems_consoles
health_news
infectious_diseases
law_enf
lottos
mobiles
online_vids
scifi_fantasy
sport_news
tv_shows
voice_vid_chat
weather

In [65]:
#checking that cat list is same length as number of cat dfs (21)
len(cats_names_list)

21

In [78]:
#creating cols for states df dict
cols_for_dict_list = ['time'] + cats_names_list + ['covid_cases'] + ['stay_at_home'] + ['mass_gathering_ban']

In [79]:
#creating a dictionary with states as keys, and dfs with cat data for each state as vals
states_info_df_dict = {}
for state in [x for x in states_abbrev_df['state_abbrev']]:
    states_info_df_dict[state] = pd.DataFrame(columns=cols_for_dict_list)

In [80]:
#checking length of states df dict - should be same as states list len (51)
len(states_info_df_dict)

51

In [84]:
#appending info to each df and saving it to a csv
for x in range(0, len(states_abbrev_df)):
    target_state = states_abbrev_df.iloc[x, 1]
    for key, value in combo_cats_dict.items():
        states_info_df_dict[target_state]['time'] = value['time']
        states_info_df_dict[target_state][key] = value[target_state]
        states_info_df_dict[target_state]['stay_at_home'] = 'False'
        states_info_df_dict[target_state]['mass_gathering_ban'] = 'False'
    print(states_info_df_dict[target_state])
    output_path = f'google_trends_csvs/state_csvs/{target_state}_cat_data.csv'
    states_info_df_dict[target_state].to_csv(output_path, index=False)

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  80     71              76         73
1    2019-01-13                  80     73              78         82
2    2019-01-20                  75     73              73         82
3    2019-01-27                  74     72              73         79
4    2019-02-03                  76     74              77         84
..          ...                 ...    ...             ...        ...
98   2020-11-22                  65     66              64         48
99   2020-11-29                  66     69              71         61
100  2020-12-06                  67     69              68         61
101  2020-12-13                  67     68              70         56
102  2020-12-20                  72     66              74         49

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  60                    0      67              16
1                  72                    0      67              14
2                  67                    0      57              11
3                  68                    0      60              18
4                  58                    0      64              17
..                ...                  ...     ...             ...
98                 65                    1      66              12
99                 57                    1      57              12
100                59                    1      56              13
101                60                    1      57              16
102                67                    0      63              10

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     90  ...       67           92             93
1                     89  ...       68           84             53
2                     94  ...       64           91             76
3                     93  ...       61           79             49
4                     78  ...       56           82             47
..                   ...  ...      ...          ...            ...
98                    72  ...       58           65             68
99                    64  ...       62           67             74
100                   67  ...       64           65            100
101                   78  ...       60           73             90
102                   73  ...       67           71             94

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            59        81              45       48          NaN         False
1            58        84              44       66          NaN         False
2            51        78              50       72          NaN         False
3            53        80              46      100          NaN         False
4            82        82              48       54          NaN         False
..          ...       ...             ...      ...          ...           ...
98           43        68              39       44          NaN         False
99           43        65              57       54          NaN         False
100          48        71              54       41          NaN         False
101          69        67              57       53          NaN         False
102          50        71              28       55          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  80     73              79         90
1    2019-01-13                  90     72              81         76
2    2019-01-20                  79     68              85         85
3    2019-01-27                  81     68              87         76
4    2019-02-03                  82     65              77         95
..          ...                 ...    ...             ...        ...
98   2020-11-22                  71     58              62         40
99   2020-11-29                  71     58              68         57
100  2020-12-06                  68     57              62         49
101  2020-12-13                  65     55              73         59
102  2020-12-20                  76     53              66         55

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  49                    0      72              10
1                  56                    0      65              29
2                  74                    0      61              29
3                  48                    0      59              39
4                  69                    0      64               9
..                ...                  ...     ...             ...
98                 46                    1      67              43
99                 49                    1      58               8
100                67                    1      53              26
101                51                    1      68               0
102                59                    0      94              19

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     81  ...       66           80             61
1                     88  ...       81           98             30
2                     66  ...       59           82             30
3                     69  ...       65           75             45
4                     44  ...       50           93             33
..                   ...  ...      ...          ...            ...
98                    62  ...       55           64             73
99                    58  ...       73           63             39
100                   47  ...       56           60             69
101                   62  ...       72           75             67
102                   80  ...       66           72             44

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            54        76              42       97          NaN         False
1            66        78              56       75          NaN         False
2            18        78              68       68          NaN         False
3            48        72              69       68          NaN         False
4            53        69              27       74          NaN         False
..          ...       ...             ...      ...          ...           ...
98            5        66              49       60          NaN         False
99           36        53              72       60          NaN         False
100           5        69              12       52          NaN         False
101          21        70              50       53          NaN         False
102          41        79              14       59          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  98     75              89         77
1    2019-01-13                  95     78              86         88
2    2019-01-20                  95     77              83         82
3    2019-01-27                  93     77              84         83
4    2019-02-03                  95     76              86         87
..          ...                 ...    ...             ...        ...
98   2020-11-22                  85     68              76         57
99   2020-11-29                  83     68              80         64
100  2020-12-06                  90     68              75         67
101  2020-12-13                  80     70              79         66
102  2020-12-20                  88     68              82         56

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  64                    0      67              22
1                  75                    0      63              27
2                  66                    0      58              30
3                  67                    0      60              24
4                  63                    0      60              30
..                ...                  ...     ...             ...
98                 63                    1      63              16
99                 57                    1      61              13
100                64                    1      57              14
101                63                    1      56              11
102                61                    0      65              12

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     88  ...       61           77             46
1                     78  ...       57           81             43
2                     72  ...       58           82             36
3                     74  ...       58           78             38
4                     65  ...       54           75             36
..                   ...  ...      ...          ...            ...
98                    66  ...       63           68             67
99                    62  ...       59           70             79
100                   59  ...       58           70             80
101                   64  ...       60           67             85
102                   75  ...       61           70             77

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            69        90              61       45          NaN         False
1            61        88              45       52          NaN         False
2            58        84              73       34          NaN         False
3            54        85              73       42          NaN         False
4            59        85              47       57          NaN         False
..          ...       ...             ...      ...          ...           ...
98           42        77              44       28          NaN         False
99           45        77              55       26          NaN         False
100          50        81              57       38          NaN         False
101          58        78              61       31          NaN         False
102          57        81              38       30          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  96     73              88         82
1    2019-01-13                  97     74              89         87
2    2019-01-20                  94     71              86         81
3    2019-01-27                  91     76              88         88
4    2019-02-03                  92     77              88         88
..          ...                 ...    ...             ...        ...
98   2020-11-22                  78     67              76         50
99   2020-11-29                  82     66              82         57
100  2020-12-06                  83     69              82         59
101  2020-12-13                  83     71              79         56
102  2020-12-20                  89     71              82         49

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  74                    0      70              15
1                  64                    0      65              24
2                  69                    0      70              27
3                  58                    0      72              14
4                  66                    0      64              22
..                ...                  ...     ...             ...
98                 59                    1      62               7
99                 73                    1      63               8
100                68                    1      62               4
101                70                    1      63              20
102                76                    0      67               5

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     83  ...       71           84             63
1                     71  ...       66           88             51
2                     79  ...       62           85             54
3                     65  ...       63           78             66
4                     58  ...       61           90             48
..                   ...  ...      ...          ...            ...
98                    65  ...       52           63             67
99                    48  ...       55           64             60
100                   65  ...       65           65             70
101                   56  ...       64           70             72
102                   63  ...       68           70             89

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            56        80              52       63          NaN         False
1            69        88              52       81          NaN         False
2            52        79              65       75          NaN         False
3            56        78              66       68          NaN         False
4            73        79              87       80          NaN         False
..          ...       ...             ...      ...          ...           ...
98           43        65              45       51          NaN         False
99           62        67              67       57          NaN         False
100          38        68              55       52          NaN         False
101          64        69              79       76          NaN         False
102          31        76              36       53          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  98     82              95         80
1    2019-01-13                  96     81              89         82
2    2019-01-20                  88     78              90         79
3    2019-01-27                  93     78              89         82
4    2019-02-03                  89     79              88         81
..          ...                 ...    ...             ...        ...
98   2020-11-22                  74     68              73         51
99   2020-11-29                  76     72              78         61
100  2020-12-06                  78     70              76         63
101  2020-12-13                  75     69              75         62
102  2020-12-20                  81     69              77         51

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  70                    0      71              24
1                  72                    0      66              27
2                  67                    0      58              29
3                  65                    0      63              32
4                  61                    0      60              25
..                ...                  ...     ...             ...
98                 56                    1      57              16
99                 52                    1      54              17
100                55                    1      51              20
101                54                    1      56              16
102                61                    0      57              14

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     86  ...       53           84             56
1                     78  ...       52           86             56
2                     74  ...       50           83             54
3                     70  ...       52           82             55
4                     67  ...       49           81             51
..                   ...  ...      ...          ...            ...
98                    64  ...       50           62             71
99                    62  ...       49           67             75
100                   62  ...       46           68             82
101                   64  ...       46           68             91
102                   70  ...       48           69             91

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            87        92              64       66          NaN         False
1            74        88              59       82          NaN         False
2            71        87              51       37          NaN         False
3            74        85              67       75          NaN         False
4            73        85              62       88          NaN         False
..          ...       ...             ...      ...          ...           ...
98           51        73              38       23          NaN         False
99           50        72              56       21          NaN         False
100          54        74              54       26          NaN         False
101          60        73              55       30          NaN         False
102          52        85              34       32          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  97     66              97         82
1    2019-01-13                  93     68              96         89
2    2019-01-20                  93     66              94         83
3    2019-01-27                  90     67              91         90
4    2019-02-03                  92     70              91         86
..          ...                 ...    ...             ...        ...
98   2020-11-22                  78     56              75         54
99   2020-11-29                  80     59              81         63
100  2020-12-06                  84     59              79         68
101  2020-12-13                  80     60              82         67
102  2020-12-20                  85     60              82         55

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  77                    0      68              11
1                  70                    0      64              24
2                  70                    0      57              20
3                  66                    0      64              25
4                  68                    0      55              28
..                ...                  ...     ...             ...
98                 66                    1      61              11

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  93     79              87         79
1    2019-01-13                  89     81              89         83
2    2019-01-20                  89     79              85         85
3    2019-01-27                  87     77              83         81
4    2019-02-03                  88     78              84         83
..          ...                 ...    ...             ...        ...
98   2020-11-22                  75     73              76         55
99   2020-11-29                  80     73              81         69
100  2020-12-06                  79     72              80         71
101  2020-12-13                  81     75              80         70
102  2020-12-20                  83     74              87         56

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  68                    0      67              23
1                  69                    0      65              20
2                  68                    0      59              27
3                  64                    0      61              23
4                  60                    0      60              28
..                ...                  ...     ...             ...
98                 62                    1      58              15
99                 60                    1      54              19
100                60                    1      53              18
101                58                    1      58              16
102                64                    0      58              14

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     83  ...       60           86             47
1                     77  ...       61           88             49
2                     78  ...       61           90             48
3                     76  ...       58           87             46
4                     66  ...       54           86             49
..                   ...  ...      ...          ...            ...
98                    70  ...       58           72             72
99                    66  ...       58           81             74
100                   66  ...       54           81             80
101                   63  ...       55           81             87
102                   75  ...       63           75             82

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            75        85              54       60          NaN         False
1            71        83              54       70          NaN         False
2            66        83              54       93          NaN         False
3            61        82              64      100          NaN         False
4            79        83              63       53          NaN         False
..          ...       ...             ...      ...          ...           ...
98           48        73              42       37          NaN         False
99           46        71              70       59          NaN         False
100          50        74              56       57          NaN         False
101          63        72              67       57          NaN         False
102          52        76              45       68          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  85     68              83         72
1    2019-01-13                  85     71              88         85
2    2019-01-20                  85     73              85         82
3    2019-01-27                  89     75              87         85
4    2019-02-03                  83     73              83         80
..          ...                 ...    ...             ...        ...
98   2020-11-22                  77     70              78         53
99   2020-11-29                  79     75              84         66
100  2020-12-06                  84     75              88         67
101  2020-12-13                  83     76              83         65
102  2020-12-20                  87     74              89         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  57                    0      61              15
1                  72                    0      61              17
2                  64                    0      56              16
3                  63                    0      69              22
4                  59                    0      56              20
..                ...                  ...     ...             ...
98                 61                    1      59               7
99                 64                    1      60              14
100                62                    1      53              13
101                64                    2      56              18
102                68                    1      58              13

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     83  ...       55           77             63
1                     85  ...       57           85             48
2                     81  ...       57           91             61
3                     75  ...       59           90             53
4                     69  ...       54           79             46
..                   ...  ...      ...          ...            ...
98                    78  ...       59           64             67
99                    71  ...       59           74             82
100                   82  ...       59           71             70
101                   77  ...       57           78             92
102                   83  ...       66           76             92

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            76        82              65       51          NaN         False
1            67        85              48       64          NaN         False
2            69        84              64       69          NaN         False
3            70        85              79      100          NaN         False
4            85        84              65       54          NaN         False
..          ...       ...             ...      ...          ...           ...
98           58        76              42       44          NaN         False
99           55        78              62       59          NaN         False
100          54        85              62       43          NaN         False
101          87        78              56       57          NaN         False
102          53        81              36       59          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                 100     84             100         90
1    2019-01-13                  98     82              96         91
2    2019-01-20                  92     84              89         89
3    2019-01-27                  93     82              90         92
4    2019-02-03                  94     89              96         91
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     75              76         59
99   2020-11-29                  77     76              76         70
100  2020-12-06                  73     74              74         67
101  2020-12-13                  72     72              71         57
102  2020-12-20                  83     81              78         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  82                    0      87              13
1                  80                    0      85              24
2                  70                    0      76              31
3                  71                    0      70              29
4                  83                    0      67              26
..                ...                  ...     ...             ...
98                 52                    1      67              14
99                 61                    1      66              14
100                63                    1      58               9
101                61                    1      58              19
102                50                    0      69               8

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     90  ...       68           83             27
1                     68  ...       62           86             61
2                     77  ...       56           98             53
3                     65  ...       63           74             31
4                     65  ...       61           83             27
..                   ...  ...      ...          ...            ...
98                    68  ...       65           57             66
99                    48  ...       65           62             79
100                   53  ...       63           60             52
101                   41  ...       55           62             59
102                   82  ...       62           67             83

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            83        96              33       36          NaN         False
1            56        85              14       49          NaN         False
2            72        80               9       43          NaN         False
3            35        90              14       77          NaN         False
4            62        91              32       56          NaN         False
..          ...       ...             ...      ...          ...           ...
98           33        80              29       34          NaN         False
99           51        75              61       26          NaN         False
100          41        62              17       22          NaN         False
101          40        73              30       27          NaN         False
102          34        79              14       30          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  92     60              91         86
1    2019-01-13                  91     64              86         82
2    2019-01-20                  89     64              87         93
3    2019-01-27                  89     65              84         88
4    2019-02-03                  89     66              86         86
..          ...                 ...    ...             ...        ...
98   2020-11-22                  77     59              75         53
99   2020-11-29                  83     57              76         64
100  2020-12-06                  79     63              76         68
101  2020-12-13                  79     61              76         68
102  2020-12-20                  87     62              77         60

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  68                    0      72              15
1                  87                    0      80              18
2                  79                    0      57              26
3                  71                    0      65              32
4                  69                    0      60              20
..                ...                  ...     ...             ...
98                 66                    1      69              10
99                 71                    1      66               8
100                78                    1      58              26
101                69                    1      58              13
102                72                    0      75              11

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     74  ...       64           84             49
1                     75  ...       53           87             48
2                     78  ...       57           80             43
3                     76  ...       72           87             46
4                     76  ...       61           78             55
..                   ...  ...      ...          ...            ...
98                    64  ...       69           62             63
99                    59  ...       54           69             73
100                   65  ...       66           71             81
101                   54  ...       60           71             84
102                   58  ...       65           81             63

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            57        89              53       53          NaN         False
1            48        87              48       65          NaN         False
2            47        79              33       48          NaN         False
3            54        84              24       49          NaN         False
4            53        85              32       81          NaN         False
..          ...       ...             ...      ...          ...           ...
98           37        77              25       43          NaN         False
99           57        74              66       37          NaN         False
100          57        77              62       43          NaN         False
101          53        75              47       67          NaN         False
102          44        74              18       55          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  91     63              92         71
1    2019-01-13                  92     67              97         82
2    2019-01-20                  89     67              95         80
3    2019-01-27                  91     66              94         69
4    2019-02-03                  90     72              97         78
..          ...                 ...    ...             ...        ...
98   2020-11-22                  73     55              83         47
99   2020-11-29                  76     57              88         54
100  2020-12-06                  79     62              85         57
101  2020-12-13                  76     58              86         58
102  2020-12-20                  81     59              87         48

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  64                    0      67              22
1                  74                    0      68              30
2                  71                    0      63              29
3                  62                    0      65              26
4                  62                    1      62              32
..                ...                  ...     ...             ...
98                 54                    1      60              18
99                 55                    1      55              19
100                56                    1      58              19
101                55                    1      58              18
102                60                    0      60              14

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     76  ...       51           85             58
1                     80  ...       51           92             55
2                     74  ...       49           93             61
3                     77  ...       47           87             62
4                     65  ...       48           89             60
..                   ...  ...      ...          ...            ...
98                    67  ...       45           68             80
99                    59  ...       49           69             81
100                   65  ...       44           74             87
101                   67  ...       46           77             95
102                   71  ...       50           77             99

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            66        83              40       39          NaN         False
1            67        84              47       58          NaN         False
2            65        87              53       64          NaN         False
3            63        85              54      100          NaN         False
4            67        86              51       50          NaN         False
..          ...       ...             ...      ...          ...           ...
98           47        75              38       25          NaN         False
99           53        75              55       22          NaN         False
100          49        76              40       24          NaN         False
101          49        75              46       25          NaN         False
102          59        83              26       29          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  90     67              92         82
1    2019-01-13                  88     68              90         86
2    2019-01-20                  89     69              87         83
3    2019-01-27                  91     67              87         79
4    2019-02-03                  90     74              92         90
..          ...                 ...    ...             ...        ...
98   2020-11-22                  78     63              75         55
99   2020-11-29                  77     66              86         58
100  2020-12-06                  80     63              84         67
101  2020-12-13                  78     65              82         62
102  2020-12-20                  85     66              86         55

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  72                    0      66              25
1                  77                    0      67              13
2                  68                    0      63              24
3                  71                    0      67              30
4                  63                    0      62              36
..                ...                  ...     ...             ...
98                 70                    1      65              16

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  84     68              82         74
1    2019-01-13                  81     70              78         74
2    2019-01-20                  82     65              76         67
3    2019-01-27                  80     68              79         73
4    2019-02-03                  82     70              78         75
..          ...                 ...    ...             ...        ...
98   2020-11-22                  70     59              66         50
99   2020-11-29                  74     62              70         55
100  2020-12-06                  74     63              72         55
101  2020-12-13                  73     63              74         56
102  2020-12-20                  77     60              69         48

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  71                    0      71              18
1                  69                    0      76              17
2                  70                    0      63              20
3                  66                    0      71              18
4                  73                    0      68              24
..                ...                  ...     ...             ...
98                 54                    1      66              12
99                 59                    1      67              19
100                54                    1      59              19
101                60                    1      69              17
102                56                    0      70               9

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     86  ...       63           75             48
1                     78  ...       68           78             48
2                     82  ...       56           73             59
3                     70  ...       58           69             41
4                     79  ...       58           76             42
..                   ...  ...      ...          ...            ...
98                    65  ...       53           53             51
99                    64  ...       55           61             62
100                   70  ...       57           62             69
101                   72  ...       63           63             73
102                   69  ...       56           61             76

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            73        86              35       64          NaN         False
1            73        82              47       69          NaN         False
2            61        84              58       80          NaN         False
3            54        78              41      100          NaN         False
4            63        81              50       61          NaN         False
..          ...       ...             ...      ...          ...           ...
98           32        70              39       43          NaN         False
99           39        67              59       49          NaN         False
100          42        72              45       37          NaN         False
101          44        70              75       49          NaN         False
102          41        71              29       53          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  95     79              85         78
1    2019-01-13                  93     82              82         84
2    2019-01-20                  89     76              77         89
3    2019-01-27                  84     78              79         86
4    2019-02-03                  92     81              82         91
..          ...                 ...    ...             ...        ...
98   2020-11-22                  74     71              72         55
99   2020-11-29                  79     74              79         64
100  2020-12-06                  82     74              75         67
101  2020-12-13                  78     75              75         63
102  2020-12-20                  82     74              79         56

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  85                    0      78              15
1                  73                    0      76              15
2                  78                    0      72              18
3                  74                    0      75              16
4                  76                    0      63              19
..                ...                  ...     ...             ...
98                 70                    1      59              11
99                 73                    1      62              12
100                70                    1      54              14
101                64                    1      59              14
102                72                    0      63              15

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     75  ...       67           93             72
1                     78  ...       73           99             48
2                     59  ...       68           92             58
3                     66  ...       70           86             52
4                     57  ...       65           89             59
..                   ...  ...      ...          ...            ...
98                    68  ...       58           65             57
99                    60  ...       67           75             64
100                   68  ...       63           71             73
101                   67  ...       66           77             83
102                   74  ...       68           78             92

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            64        75              70       33          NaN         False
1            65        81              46       46          NaN         False
2            63        77              53       46          NaN         False
3            52        74              67       50          NaN         False
4            91        84              49       40          NaN         False
..          ...       ...             ...      ...          ...           ...
98           48        67              54       36          NaN         False
99           40        67              67       36          NaN         False
100          48        73              65       29          NaN         False
101          68        62              66       38          NaN         False
102          56        69              37       35          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  90     70              92         83
1    2019-01-13                  86     71              87         84
2    2019-01-20                  89     69              82         75
3    2019-01-27                  84     68              84         70
4    2019-02-03                  88     71              89         72
..          ...                 ...    ...             ...        ...
98   2020-11-22                  78     64              72         43
99   2020-11-29                  75     63              77         56
100  2020-12-06                  73     64              76         56
101  2020-12-13                  73     61              70         51
102  2020-12-20                  76     60              78         48

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  58                    0      59              31
1                  70                    0      52              31
2                  62                    0      56              21
3                  47                    0      53              37
4                  42                    0      54              27
..                ...                  ...     ...             ...
98                 66                    1      57              19
99                 47                    1      53              24
100                52                    1      47              13
101                38                    1      53              16
102                46                    0      59              12

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     77  ...       49           95             42
1                     72  ...       46           89             35
2                     69  ...       56           91             45
3                     63  ...       62           80             33
4                     55  ...       54           81             45
..                   ...  ...      ...          ...            ...
98                    61  ...       49           61             67
99                    43  ...       55           52             72
100                   44  ...       49           66             83
101                   46  ...       55           72             57
102                   65  ...       58           71             64

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            82        90              46       87          NaN         False
1            52        83              28       96          NaN         False
2            66        89              11       86          NaN         False
3            58        88              50       81          NaN         False
4            57        82              56       60          NaN         False
..          ...       ...             ...      ...          ...           ...
98           46        85              39       53          NaN         False
99           40        69              64       69          NaN         False
100          25        76              55       54          NaN         False
101          36        73              70       79          NaN         False
102          48        75              22       59          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  94     75              82         84
1    2019-01-13                  93     75              85         83
2    2019-01-20                  90     75              86         84
3    2019-01-27                  87     77              82         76
4    2019-02-03                  87     81              86         85
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     71              78         67
99   2020-11-29                  85     71              81         75
100  2020-12-06                  85     72              80         74
101  2020-12-13                  84     72              78         74
102  2020-12-20                  92     74              84         67

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  68                    0      69              25
1                  73                    0      70              25
2                  78                    0      62              34
3                  64                    0      64              29
4                  71                    1      63              33
..                ...                  ...     ...             ...
98                 69                    1      62              25
99                 64                    1      56              22
100                71                    1      59              28
101                63                    1      59              19
102                75                    1      60              16

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     76  ...       62           88             41
1                     78  ...       58           84             57
2                     71  ...       55           88             49
3                     76  ...       56           83             52
4                     57  ...       57           86             48
..                   ...  ...      ...          ...            ...
98                    78  ...       60           68             80
99                    71  ...       58           79             79
100                   62  ...       54           78             87
101                   68  ...       51           75            100
102                   85  ...       59           79             97

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            66        88              40       76          NaN         False
1            70        85              47      100          NaN         False
2            63        88              45       58          NaN         False
3            71        82              61      100          NaN         False
4            70        89              43       57          NaN         False
..          ...       ...             ...      ...          ...           ...
98           56        84              38       33          NaN         False
99           56        81              47       41          NaN         False
100          59        84              41       33          NaN         False
101          64        77              45       80          NaN         False
102          66        89              43       44          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  96     78             100         78
1    2019-01-13                  89     77              97         76
2    2019-01-20                  93     74              96         68
3    2019-01-27                  88     77              92         76
4    2019-02-03                  90     79              92         77
..          ...                 ...    ...             ...        ...
98   2020-11-22                  75     65              76         49
99   2020-11-29                  74     68              79         56
100  2020-12-06                  76     67              76         56
101  2020-12-13                  73     66              76         54
102  2020-12-20                  80     65              83         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  76                    0      74              24
1                  82                    0      73              27
2                  84                    0      63              32
3                  65                    0      63              40
4                  68                    0      59              39
..                ...                  ...     ...             ...
98                 60                    1      59              14
99                 56                    1      58              20
100                61                    1      60              19
101                57                    1      61              19
102                68                    0      61              16

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     94  ...       55           81             54
1                     82  ...       60           87             56
2                     88  ...       54           87             54
3                     77  ...       57           91             55
4                     70  ...       52           92             59
..                   ...  ...      ...          ...            ...
98                    70  ...       54           67             83
99                    61  ...       48           71             83
100                   58  ...       51           71             72
101                   61  ...       46           73             95
102                   79  ...       55           76            100

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            76        90              67       57          NaN         False
1            67        86              72       91          NaN         False
2            68        87              53       75          NaN         False
3            61        86              51       82          NaN         False
4            78        86              62       55          NaN         False
..          ...       ...             ...      ...          ...           ...
98           53        77              34       40          NaN         False
99           55        70              54       58          NaN         False
100          59        74              52       43          NaN         False
101          54        74              54       87          NaN         False
102          61        81              47       46          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  98     66              90         83
1    2019-01-13                  91     69              84         86
2    2019-01-20                  89     65              86         78
3    2019-01-27                  88     63              83         66
4    2019-02-03                  89     66              84         74
..          ...                 ...    ...             ...        ...
98   2020-11-22                  78     55              74         59
99   2020-11-29                  80     56              83         62
100  2020-12-06                  79     57              78         68
101  2020-12-13                  80     57              77         66
102  2020-12-20                  84     58              80         61

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  72                    0      71              25
1                  76                    0      67              21
2                  66                    0      63              23
3                  72                    0      65              26
4                  63                    0      65              28
..                ...                  ...     ...             ...
98                 64                    1      64              17

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  87     65             100         88
1    2019-01-13                  81     65              95         89
2    2019-01-20                  77     63              80         77
3    2019-01-27                  77     67              83         74
4    2019-02-03                  77     65              81         79
..          ...                 ...    ...             ...        ...
98   2020-11-22                  68     55              68         53
99   2020-11-29                  70     56              74         63
100  2020-12-06                  71     56              72         61
101  2020-12-13                  71     58              74         63
102  2020-12-20                  76     61              72         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  99                    0      71              20
1                  86                    0      69              27
2                  76                    0      62              24
3                  78                    0      67              18
4                  85                    0      59              19
..                ...                  ...     ...             ...
98                 68                    1      60              19
99                 74                    1      57              14
100                73                    1      61              14
101                77                    1      67              18
102                79                    0      65              14

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     85  ...       56           86             44
1                     80  ...       50           85             41
2                     81  ...       51           82             40
3                     79  ...       51           83             38
4                     63  ...       51           80             44
..                   ...  ...      ...          ...            ...
98                    62  ...       56           71             67
99                    54  ...       51           72             65
100                   65  ...       52           71             76
101                   62  ...       47           73             67
102                   67  ...       53           74             73

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            66        92              42       32          NaN         False
1            57        91              50       36          NaN         False
2            46        87              59       59          NaN         False
3            44        87              77      100          NaN         False
4            49        90              53       76          NaN         False
..          ...       ...             ...      ...          ...           ...
98           35        84              22       23          NaN         False
99           36        78              57       21          NaN         False
100          43        81              55       23          NaN         False
101          42        81              53       26          NaN         False
102          44        87              35       50          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  63     60              69         59
1    2019-01-13                  65     62              70         64
2    2019-01-20                  62     60              69         63
3    2019-01-27                  58     63              68         63
4    2019-02-03                  61     61              65         66
..          ...                 ...    ...             ...        ...
98   2020-11-22                  53     59              62         40
99   2020-11-29                  54     62              67         50
100  2020-12-06                  57     62              67         46
101  2020-12-13                  56     63              66         47
102  2020-12-20                  60     62              70         39

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  45                    0      52              18
1                  64                    0      76              28
2                  67                    0      52              28
3                  68                    0      67              26
4                  46                    0      70              23
..                ...                  ...     ...             ...
98                 53                    1      59              16
99                 53                    1      64              24
100                49                    1      70               7
101                51                    1      62              14
102                66                    0      73              18

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     66  ...       76           71             50
1                     81  ...       69           76             38
2                     72  ...       67           77             56
3                     81  ...       73           65             51
4                     69  ...       69           79             40
..                   ...  ...      ...          ...            ...
98                    69  ...       42           57             60
99                    57  ...       55           62             51
100                   73  ...       47           57             61
101                   57  ...       52           53             67
102                   70  ...       53           60             54

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            74        68              16       51          NaN         False
1            50        64              40       70          NaN         False
2            47        67              11       71          NaN         False
3            51        65              21       89          NaN         False
4            88        70              24       56          NaN         False
..          ...       ...             ...      ...          ...           ...
98           36        59              21       50          NaN         False
99           38        59              35       54          NaN         False
100          52        63              31       43          NaN         False
101          81        61              38       59          NaN         False
102          36        61              21       57          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  83     65              80         85
1    2019-01-13                  82     64              83         85
2    2019-01-20                  83     64              85         80
3    2019-01-27                  81     66              84         82
4    2019-02-03                  86     68              86         81
..          ...                 ...    ...             ...        ...
98   2020-11-22                  68     55              66         51
99   2020-11-29                  66     58              75         59
100  2020-12-06                  67     57              71         56
101  2020-12-13                  69     57              70         56
102  2020-12-20                  72     58              76         50

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  74                    1      76              39
1                  76                    1      71              38
2                  84                    1      66              38
3                  75                    2      69              56
4                  60                    1      70              37
..                ...                  ...     ...             ...
98                 61                    2      60              15
99                 60                    2      60              15
100                53                    2      56              22
101                65                    2      60              16
102                68                    1      66              11

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     70  ...       66           90             50
1                     74  ...       65           85             53
2                     64  ...       60           86             57
3                     71  ...       64           85             56
4                     63  ...       63           87             53
..                   ...  ...      ...          ...            ...
98                    65  ...       66           62             68
99                    61  ...       55           67             69
100                   61  ...       55           65             63
101                   58  ...       64           65             71
102                   66  ...       60           71             90

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            70        85              60       82          NaN         False
1            58        88              56       92          NaN         False
2            54        91              48       67          NaN         False
3            57        88              68       77          NaN         False
4            48        87              61       78          NaN         False
..          ...       ...             ...      ...          ...           ...
98           38        70              39       37          NaN         False
99           46        71              81       36          NaN         False
100          50        74              66       35          NaN         False
101          52        72              59       38          NaN         False
102          43        79              22       41          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  89     63              95         98
1    2019-01-13                  89     68              85         77
2    2019-01-20                  87     65              89         85
3    2019-01-27                  85     68              89         87
4    2019-02-03                  85     64              86         70
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     63              77         60
99   2020-11-29                  78     61              79         64
100  2020-12-06                  80     64              78         71
101  2020-12-13                  82     67              82         62
102  2020-12-20                  90     64              75         56

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  52                    0      71               9
1                  62                    0      69               9
2                  52                    0      56               9
3                  68                    0      53              14
4                  63                    0      55               9
..                ...                  ...     ...             ...
98                 60                    1      57               0
99                 56                    1      55               8
100                57                    1      52              12
101                72                    1      53               8
102                69                    0      68               0

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     73  ...       71           84             53
1                     72  ...       65           90             29
2                     78  ...       81           99             43
3                     79  ...       62           93             29
4                     65  ...       65           85             34
..                   ...  ...      ...          ...            ...
98                    70  ...       65           69             41
99                    52  ...       75           68             88
100                   60  ...       66           76             82
101                   71  ...       77           80             78
102                   72  ...       61           89             68

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            63        72              39       36          NaN         False
1            69        81              29       47          NaN         False
2            64        72              66       53          NaN         False
3            47        67              28       53          NaN         False
4            64        85              57       83          NaN         False
..          ...       ...             ...      ...          ...           ...
98           65        82              67       33          NaN         False
99           33        79              67       24          NaN         False
100          34        74              60       38          NaN         False
101          47        73              34       37          NaN         False
102          63        81              19       41          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  95     65              94         81
1    2019-01-13                  98     65              98         87
2    2019-01-20                  95     62              89         77
3    2019-01-27                  91     65              99         82
4    2019-02-03                  95     66              92         90
..          ...                 ...    ...             ...        ...
98   2020-11-22                  78     56              78         48
99   2020-11-29                  75     54              85         58
100  2020-12-06                  74     56              81         56
101  2020-12-13                  75     58              75         53
102  2020-12-20                  85     57              84         46

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  79                    0      77              29
1                  91                    0      80              22
2                  61                    0      67              24
3                  67                    0      70              35
4                  51                    0      63              28
..                ...                  ...     ...             ...
98                 71                    1      67              17
99                 55                    1      56               0
100                58                    1      57              15
101                59                    1      61               6
102                62                    0      63               4

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     81  ...       59           98             50
1                     87  ...       62           82             35
2                     85  ...       58           87             55
3                     74  ...       58           83             51
4                     85  ...       60           88             29
..                   ...  ...      ...          ...            ...
98                    59  ...       59           68             60
99                    60  ...       61           69             62
100                   59  ...       58           68             49
101                   63  ...       63           67             56
102                   67  ...       70           75            100

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            41        85              59       47          NaN         False
1            43        88              40       78          NaN         False
2            43        90              53       69          NaN         False
3            36        86              58       64          NaN         False
4            63        90              70       60          NaN         False
..          ...       ...             ...      ...          ...           ...
98           36        72              35       34          NaN         False
99           30        68              62       27          NaN         False
100          28        66              47       42          NaN         False
101          48        70              44       36          NaN         False
102          47        77              17       50          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  92     78              89         79
1    2019-01-13                  94     77              84         78
2    2019-01-20                  85     73              85         76
3    2019-01-27                  87     74              82         77
4    2019-02-03                  90     74              81         81
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     70              81         57
99   2020-11-29                  81     71              84         65
100  2020-12-06                  82     73              81         70
101  2020-12-13                  79     74              80         66
102  2020-12-20                  88     71              87         57

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  78                    0      76              22
1                  73                    0      64              31
2                  70                    0      61              25
3                  65                    0      63              24
4                  72                    0      66              14
..                ...                  ...     ...             ...
98                 65                    1      56              11

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  93     65              86         88
1    2019-01-13                  95     68              85         95
2    2019-01-20                  92     70              76         87
3    2019-01-27                  92     68              83         89
4    2019-02-03                  91     69              80         89
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     58              64         62
99   2020-11-29                  84     62              74         72
100  2020-12-06                  84     59              71         73
101  2020-12-13                  83     60              79         67
102  2020-12-20                  90     62              74         62

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  68                    0      65              26
1                  68                    0      68              36
2                  82                    0      53              21
3                  54                    0      66              28
4                  67                    0      53              35
..                ...                  ...     ...             ...
98                 54                    1      57              19
99                 61                    1      53              29
100                59                    1      56              12
101                60                    1      58              36
102                72                    0      58              14

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     78  ...       67           80             41
1                     79  ...       61           84             44
2                     73  ...       63           78             46
3                     77  ...       47           72             48
4                     67  ...       57           83             47
..                   ...  ...      ...          ...            ...
98                    78  ...       53           61             69
99                    67  ...       56           64             83
100                   69  ...       58           67             65
101                   72  ...       58           64             78
102                   69  ...       60           71             91

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            58        91              35       58          NaN         False
1            53        83              35       58          NaN         False
2            63        91              29       49          NaN         False
3            42        74              39       44          NaN         False
4            56        81              58       54          NaN         False
..          ...       ...             ...      ...          ...           ...
98           47        77              48       43          NaN         False
99           29        76              68       43          NaN         False
100          64        77              56       46          NaN         False
101          38        79              84       43          NaN         False
102          39        85              38       38          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  91     56              83         71
1    2019-01-13                  94     66              92         77
2    2019-01-20                  92     65              91         74
3    2019-01-27                  90     64              86         72
4    2019-02-03                  96     75              98         80
..          ...                 ...    ...             ...        ...
98   2020-11-22                  72     56              68         51
99   2020-11-29                  75     60              77         57
100  2020-12-06                  76     61              80         63
101  2020-12-13                  76     63              78         59
102  2020-12-20                  77     55              76         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  66                    0      71              27
1                  71                    0      71              29
2                  76                    0      63              33
3                  64                    0      65              32
4                  72                    0      62              32
..                ...                  ...     ...             ...
98                 58                    1      56              19
99                 55                    1      53              21
100                59                    1      54              24
101                56                    1      54              20
102                60                    0      57              15

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     78  ...       58           87             59
1                     79  ...       63           88             58
2                     80  ...       61           89             64
3                     74  ...       56           84             66
4                     69  ...       61           90             69
..                   ...  ...      ...          ...            ...
98                    69  ...       52           69             75
99                    61  ...       54           77             78
100                   64  ...       52           78             87
101                   66  ...       51           80             92
102                   71  ...       53           77             96

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            73        83              60       62          NaN         False
1            70        85              65       92          NaN         False
2            74        88              77       85          NaN         False
3            69        83              91      100          NaN         False
4            74        84              80       67          NaN         False
..          ...       ...             ...      ...          ...           ...
98           52        68              44       43          NaN         False
99           46        68              67       50          NaN         False
100          48        71              57       45          NaN         False
101          50        69              71       84          NaN         False
102          56        72              47       55          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  95     74              93         93
1    2019-01-13                  91     71              93         86
2    2019-01-20                  88     68              84         82
3    2019-01-27                  84     68              80         83
4    2019-02-03                  87     73              84         85
..          ...                 ...    ...             ...        ...
98   2020-11-22                  72     63              72         53
99   2020-11-29                  75     62              75         61
100  2020-12-06                  76     61              74         61
101  2020-12-13                  75     62              77         58
102  2020-12-20                  79     60              77         49

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  70                    0      73              19
1                  73                    0      68              18
2                  66                    0      59              22
3                  64                    0      63              24
4                  61                    0      61              23
..                ...                  ...     ...             ...
98                 56                    1      58              15
99                 60                    1      58              17
100                62                    1      57              14
101                62                    1      54              11
102                63                    0      62              10

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     94  ...       71           81             72
1                     81  ...       70           80             53
2                     85  ...       66           77             60
3                     77  ...       62           74             59
4                     72  ...       64           76             48
..                   ...  ...      ...          ...            ...
98                    70  ...       60           60             81
99                    63  ...       60           64             81
100                   68  ...       56           63             84
101                   72  ...       54           67            100
102                   78  ...       65           66             97

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            85        89              56       68          NaN         False
1            70        85              58       66          NaN         False
2            60        79              46       66          NaN         False
3            67        82              63       69          NaN         False
4            76        83              60       51          NaN         False
..          ...       ...             ...      ...          ...           ...
98           44        67              48       40          NaN         False
99           52        65              66       48          NaN         False
100          51        70              58       40          NaN         False
101          56        70              75       59          NaN         False
102          66        73              39       56          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  96     66              96         85
1    2019-01-13                 100     74              94         81
2    2019-01-20                  87     70              88         72
3    2019-01-27                  89     75              79         74
4    2019-02-03                  87     72              81         76
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     59              81         64
99   2020-11-29                  86     65              86         79
100  2020-12-06                  84     61              84         83
101  2020-12-13                  81     65              79         66
102  2020-12-20                  83     60              74         59

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  59                    0      64               9
1                  76                    0      67              23
2                  70                    0      55               9
3                  69                    0      63              23
4                  77                    0      61              18
..                ...                  ...     ...             ...
98                 41                    1      55               0
99                 50                    1      62              20
100                66                    1      57               8
101                64                    1      47              16
102                71                    0      57              18

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     95  ...       71           75             27
1                     94  ...       74           88             40
2                     73  ...       56           87             53
3                     89  ...       47           73             40
4                     63  ...       57           77             36
..                   ...  ...      ...          ...            ...
98                    75  ...       68           65             51
99                    68  ...       67           76             47
100                   69  ...       73           66             68
101                   68  ...       63           59             84
102                   74  ...       69           78            100

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            51        87              11       34          NaN         False
1            60        93              22       41          NaN         False
2            30        89              42       65          NaN         False
3            36        79              64       90          NaN         False
4            43        76              63       83          NaN         False
..          ...       ...             ...      ...          ...           ...
98           41        76              19       19          NaN         False
99           21        78              37       25          NaN         False
100          30        83              28       26          NaN         False
101          36        78              58       31          NaN         False
102          29        75              21       42          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  97     68              91         82
1    2019-01-13                 100     71              95         88
2    2019-01-20                  92     71              90         81
3    2019-01-27                  97     69              92         76
4    2019-02-03                  96     76              93         89
..          ...                 ...    ...             ...        ...
98   2020-11-22                  79     59              74         53
99   2020-11-29                  79     60              81         59
100  2020-12-06                  84     61              78         63
101  2020-12-13                  80     60              77         63
102  2020-12-20                  85     61              77         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  75                    0      75              17
1                  79                    0      74              24
2                  76                    0      70              20
3                  73                    0      71              20
4                  72                    0      71              22
..                ...                  ...     ...             ...
98                 66                    1      62              13
99                 58                    1      63              14
100                65                    1      60              14
101                62                    1      63              15
102                70                    0      64              11

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     88  ...       70           91             61
1                     92  ...       68           98             51
2                     80  ...       60           92             67
3                     76  ...       66           94             58
4                     69  ...       61           95             61
..                   ...  ...      ...          ...            ...
98                    71  ...       57           76             70
99                    66  ...       57           77             83
100                   66  ...       58           80             78
101                   65  ...       56           82             92
102                   85  ...       58           82             90

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            66        97              39       55          NaN         False
1            59        96              48      100          NaN         False
2            57        93              39       91          NaN         False
3            48        89              56       92          NaN         False
4            68        94              51       51          NaN         False
..          ...       ...             ...      ...          ...           ...
98           48        77              38       32          NaN         False
99           42        78              50       40          NaN         False
100          51        79              52       29          NaN         False
101          62        78              54       37          NaN         False
102          52        85              31       44          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  82     69              85         74
1    2019-01-13                  81     72              83         75
2    2019-01-20                  81     70              80         81
3    2019-01-27                  79     73              84         77
4    2019-02-03                  78     74              77         74
..          ...                 ...    ...             ...        ...
98   2020-11-22                  69     59              67         46
99   2020-11-29                  69     62              71         56
100  2020-12-06                  69     64              72         60
101  2020-12-13                  68     60              69         58
102  2020-12-20                  72     66              72         45

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  69                    0      74              17
1                  91                    0      73              23
2                  76                    0      69              28
3                  70                    0      69              16
4                  69                    0      60              19
..                ...                  ...     ...             ...
98                 71                    1      63               6

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  90     66              88         81
1    2019-01-13                  89     66              85         77
2    2019-01-20                  92     64              80         72
3    2019-01-27                  92     65              85         82
4    2019-02-03                  86     65              82         77
..          ...                 ...    ...             ...        ...
98   2020-11-22                  73     55              70         51
99   2020-11-29                  74     56              73         56
100  2020-12-06                  73     60              74         54
101  2020-12-13                  69     56              63         53
102  2020-12-20                  75     56              73         50

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  69                    0      60              24
1                  80                    0      56              21
2                  70                    0      59               9
3                  69                    0      64              24
4                  44                    0      47              21
..                ...                  ...     ...             ...
98                 45                    1      58              16
99                 62                    1      53              13
100                58                    1      46               8
101                45                    1      54               3
102                46                    0      59              18

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     86  ...       68           76             39
1                     91  ...       64           87             47
2                     70  ...       69           74             44
3                     59  ...       55           84             29
4                     59  ...       49           66             38
..                   ...  ...      ...          ...            ...
98                    47  ...       45           45             67
99                    44  ...       52           60             88
100                   53  ...       52           47             71
101                   41  ...       45           51             72
102                   64  ...       56           52             86

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            35        84              21       52          NaN         False
1            38        93              15       79          NaN         False
2            44        90              45       72          NaN         False
3            48        87              41       73          NaN         False
4            48        85              20       55          NaN         False
..          ...       ...             ...      ...          ...           ...
98           42        72              23       37          NaN         False
99           30        74              49       52          NaN         False
100          39        68              36       45          NaN         False
101          42        73              37       86          NaN         False
102          43        76              25       48          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  96     78              70         87
1    2019-01-13                  95     76              73         87
2    2019-01-20                  88     80              71         81
3    2019-01-27                  93     76              70         83
4    2019-02-03                  92     78              72         88
..          ...                 ...    ...             ...        ...
98   2020-11-22                  80     70              63         55
99   2020-11-29                  80     73              68         60
100  2020-12-06                  83     76              67         55
101  2020-12-13                  82     74              68         59
102  2020-12-20                  89     76              71         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  68                    0      65              22
1                  74                    0      66              10
2                  69                    0      61              18
3                  71                    0      66              17
4                  65                    0      61              26
..                ...                  ...     ...             ...
98                 69                    1      64              11
99                 56                    1      61              13
100                65                    1      59              14
101                59                    1      67              18
102                74                    0      66              13

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     68  ...       60           92             66
1                     83  ...       61           87             54
2                     73  ...       62           83             55
3                     80  ...       61           94             43
4                     60  ...       61           81             42
..                   ...  ...      ...          ...            ...
98                    72  ...       63           70             75
99                    63  ...       65           72             74
100                   66  ...       62           68             72
101                   68  ...       62           79             94
102                   70  ...       65           77             95

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            80        91              37       59          NaN         False
1            48        79              35       68          NaN         False
2            54        89              41       68          NaN         False
3            44        83              48       69          NaN         False
4            73        89              58       57          NaN         False
..          ...       ...             ...      ...          ...           ...
98           42        71              17       47          NaN         False
99           43        69              73       59          NaN         False
100          46        75              68       44          NaN         False
101          54        74              58       68          NaN         False
102          43        71              39       66          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  93     62              89         95
1    2019-01-13                  93     67              91         85
2    2019-01-20                  91     65              90         88
3    2019-01-27                  88     65              87         91
4    2019-02-03                  93     60              90         77
..          ...                 ...    ...             ...        ...
98   2020-11-22                  81     55              81         55
99   2020-11-29                  84     61              84         59
100  2020-12-06                  82     55              77         59
101  2020-12-13                  81     54              81         49
102  2020-12-20                  87     60              74         50

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  90                    0      74              37
1                  78                    0      63              82
2                  70                    0      53              36
3                 100                    0      78              27
4                  69                    0      54              18
..                ...                  ...     ...             ...
98                 65                    1      69              24
99                 62                    1      65              24
100                49                    0      67              40
101                51                    1      62              24
102                73                    0      72              18

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     73  ...       60           86             41
1                     49  ...       78          100             56
2                     59  ...       54           83             40
3                     53  ...       72           74             71
4                     50  ...       57           75             70
..                   ...  ...      ...          ...            ...
98                    76  ...       70           60             85
99                    61  ...       57           68             84
100                   43  ...       81           64             67
101                   61  ...       84           83             96
102                   54  ...       68           78             90

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            70        77              10       30          NaN         False
1            48        74              29       57          NaN         False
2            34        70              48       56          NaN         False
3            26        74              57       76          NaN         False
4            72        77              58       63          NaN         False
..          ...       ...             ...      ...          ...           ...
98           34        75               8       23          NaN         False
99           37        68              42       25          NaN         False
100          38        63              52       24          NaN         False
101          35        58              95       28          NaN         False
102          34        72              37       50          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  83     68              83         84
1    2019-01-13                  82     69              83         90
2    2019-01-20                  79     68              78         89
3    2019-01-27                  75     68              75         84
4    2019-02-03                  77     70              76         90
..          ...                 ...    ...             ...        ...
98   2020-11-22                  68     62              67         56
99   2020-11-29                  70     62              75         66
100  2020-12-06                  71     63              72         70
101  2020-12-13                  69     63              73         66
102  2020-12-20                  74     61              73         53

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  62                    0      69              17
1                  71                    0      70              20
2                  75                    0      64              20
3                  62                    0      66              21
4                  63                    0      61              20
..                ...                  ...     ...             ...
98                 68                    1      62              14
99                 62                    1      62              17
100                61                    1      60              16
101                67                    1      60              15
102                72                    0      65              11

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     74  ...       62           94             45
1                     77  ...       66           88             44
2                     77  ...       65           86             46
3                     66  ...       65           91             44
4                     65  ...       63           86             40
..                   ...  ...      ...          ...            ...
98                    64  ...       60           71             54
99                    61  ...       60           75             66
100                   57  ...       61           74             69
101                   54  ...       60           77             74
102                   68  ...       66           73             80

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            59        88              51       54          NaN         False
1            65        88              51       64          NaN         False
2            62        87              68       77          NaN         False
3            47        83              51      100          NaN         False
4            86        84              45       68          NaN         False
..          ...       ...             ...      ...          ...           ...
98           43        69              37       43          NaN         False
99           46        76              75       56          NaN         False
100          49        79              64       41          NaN         False
101          59        74              80       53          NaN         False
102          47        76              36       61          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  91     73              87         76
1    2019-01-13                  92     74              83         84
2    2019-01-20                  91     71              84         82
3    2019-01-27                  90     72              83         82
4    2019-02-03                  91     73              88         84
..          ...                 ...    ...             ...        ...
98   2020-11-22                  79     63              77         52
99   2020-11-29                  81     64              79         65
100  2020-12-06                  83     66              78         68
101  2020-12-13                  81     66              82         64
102  2020-12-20                  84     67              82         50

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  72                    0      71              21
1                  77                    0      65              23
2                  73                    0      61              22
3                  70                    0      64              26
4                  70                    0      63              28
..                ...                  ...     ...             ...
98                 60                    1      58              15
99                 60                    1      55              17
100                67                    1      54              19
101                63                    1      55              19
102                69                    0      61              12

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     81  ...       56           77             58
1                     79  ...       58           79             50
2                     77  ...       55           75             50
3                     78  ...       54           78             50
4                     72  ...       54           79             53
..                   ...  ...      ...          ...            ...
98                    72  ...       57           61             72
99                    66  ...       56           67             73
100                   69  ...       54           68             80
101                   69  ...       54           69             88
102                   73  ...       60           67             93

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            81        84              64       59          NaN         False
1            75        83              59       73          NaN         False
2            77        84              57       73          NaN         False
3            66        79              68       74          NaN         False
4            90        86              67       77          NaN         False
..          ...       ...             ...      ...          ...           ...
98           53        74              44       56          NaN         False
99           59        71              68       58          NaN         False
100          61        76              61       49          NaN         False
101          77        71              71       63          NaN         False
102          59        76              46       52          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  98     64              96         94
1    2019-01-13                  93     63              96         86
2    2019-01-20                  92     62              89         86
3    2019-01-27                  92     61              91         87
4    2019-02-03                  93     64              91         81
..          ...                 ...    ...             ...        ...
98   2020-11-22                  79     55              77         64
99   2020-11-29                  80     56              83         70
100  2020-12-06                  81     58              82         71
101  2020-12-13                  81     57              82         69
102  2020-12-20                  86     57              82         58

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  57                    0      57              20
1                  71                    0      58              29
2                  72                    0      57              32
3                  53                    0      64              32
4                  70                    0      58              27
..                ...                  ...     ...             ...
98                 64                    1      57              22

           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  96     66             100         89
1    2019-01-13                  92     64              95         87
2    2019-01-20                  85     61              80         76
3    2019-01-27                  93     67              76         71
4    2019-02-03                  93     64              80         82
..          ...                 ...    ...             ...        ...
98   2020-11-22                  79     55              73         56
99   2020-11-29                  79     59              77         60
100  2020-12-06                  80     59              74         64
101  2020-12-13                  78     59              72         64
102  2020-12-20                  84     56              73         55

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  69                    0      74              20
1                  73                    0      72              23
2                  70                    0      62              22
3                  66                    0      72              24
4                  66                    0      65              26
..                ...                  ...     ...             ...
98                 59                    1      67              24
99                 60                    1      65              18
100                62                    1      58              19
101                54                    1      69              20
102                72                    0      68              17

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     74  ...       64           91             56
1                     79  ...       65           80             64
2                     86  ...       59           82             52
3                     78  ...       57           83             68
4                     74  ...       60           83             54
..                   ...  ...      ...          ...            ...
98                    62  ...       64           69             81
99                    65  ...       57           69             90
100                   68  ...       55           69             80
101                   69  ...       52           68             87
102                   69  ...       66           76             99

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            54        91              27       34          NaN         False
1            55        85              42       41          NaN         False
2            50        83              36       73          NaN         False
3            49        83              44      100          NaN         False
4            52        81              35       59          NaN         False
..          ...       ...             ...      ...          ...           ...
98           41        78              29       26          NaN         False
99           38        71              59       21          NaN         False
100          38        77              42       26          NaN         False
101          47        74              61       26          NaN         False
102          54        81              18       34          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]
           time  arts_entertainment  autos  beauty_fitness  books_lit  \
0    2019-01-06                  92     63              95         83
1    2019-01-13                  95     67              95         77
2    2019-01-20                  89     67              90         80
3    2019-01-27                  86     63              91         72
4    2019-02-03                  93     68              83         74
..          ...                 ...    ...             ...        ...
98   2020-11-22                  79     63              74         55
99   2020-11-29                  81     62              77         65
100  2020-12-06                  84     57              84         55
101  2020-12-13                  77     63              81         56
102  2020-12-20                  88     57              77         54

     action_adventure  campaigns_elections  celebs  discrimination  \
0                  72                    0      78               9
1                  44                    0      65               0
2                  54                    0      80               0
3                  60                    0      65               0
4                  39                    0      77              25
..                ...                  ...     ...             ...
98                 42                    1      51              15
99                 58                    1      59              29
100                51                    1      67               7
101                75                    1      78              15
102                57                    0      63              25

     entertainment_media  ...  mobiles  online_vids  scifi_fantasy  \
0                     56  ...       39           82             81
1                     68  ...       46           83             46
2                     94  ...       47           84             40
3                     55  ...       44           70             23
4                     66  ...       41           88             45
..                   ...  ...      ...          ...            ...
98                    63  ...       42           76             81
99                    59  ...       60           69             70
100                   33  ...       56           73             81
101                   36  ...       57           61             62
102                   54  ...       50           63             90

     sport_news  tv_shows  voice_vid_chat  weather  covid_cases  stay_at_home  \
0            26        72               0       47          NaN         False
1            32        94              36       56          NaN         False
2            50        82              12       65          NaN         False
3            25        85               0       54          NaN         False
4            50        95              36       78          NaN         False
..          ...       ...             ...      ...          ...           ...
98           22        65               0       27          NaN         False
99           22        77              42       36          NaN         False
100          28        83              32       39          NaN         False
101          23        70              43       47          NaN         False
102          31        70              35       44          NaN         False

     mass_gathering_ban
0                 False
1                 False
2                 False
3                 False
4                 False
..                  ...
98                False
99                False
100               False
101               False
102               False

[103 rows x 25 columns]

In [85]:
#test-reading a csv back in to see if all is well
path = 'google_trends_csvs/state_csvs/US-CA_cat_data.csv'
ca_data_df = pd.read_csv(path)
ca_data_df.head(20)

,time,arts_entertainment,autos,beauty_fitness,books_lit,action_adventure,campaigns_elections,celebs,discrimination,entertainment_media,...,mobiles,online_vids,scifi_fantasy,sport_news,tv_shows,voice_vid_chat,weather,covid_cases,stay_at_home,mass_gathering_ban
0,2019-01-06,98,82,95,80,70,0,71,24,86,...,53,84,56,87,92,64,66,NaN,False,False
1,2019-01-13,96,81,89,82,72,0,66,27,78,...,52,86,56,74,88,59,82,NaN,False,False
2,2019-01-20,88,78,90,79,67,0,58,29,74,...,50,83,54,71,87,51,37,NaN,False,False
3,2019-01-27,93,78,89,82,65,0,63,32,70,...,52,82,55,74,85,67,75,NaN,False,False
4,2019-02-03,89,79,88,81,61,0,60,25,67,...,49,81,51,73,85,62,88,NaN,False,False
5,2019-02-10,96,78,84,84,59,0,62,31,71,...,49,83,58,63,87,60,100,NaN,False,False
6,2019-02-17,96,83,88,79,66,0,78,30,73,...,54,79,54,65,85,67,72,NaN,False,False
7,2019-02-24,99,82,86,90,61,0,70,35,69,...,53,80,53,68,92,63,66,NaN,False,False
8,2019-03-03,100,86,92,88,63,0,58,77,71,...,51,80,55,76,100,73,76,NaN,False,False
9,2019-03-10,94,83,90,82,60,0,62,29,70,...,49,80,52,90,90,64,46,NaN,False,False
10,2019-03-17,88,83,91,83,62,0,53,23,71,...,48,79,50,77,84,61,52,NaN,False,False
11,2019-03-24,89,82,86,79,57,0,52,24,71,...,48,80,48,72,80,52,39,NaN,False,False
12,2019-03-31,93,80,89,81,66,0,50,22,68,...,46,75,50,75,81,60,42,NaN,False,False
13,2019-04-07,92,81,86,83,67,0,47,25,66,...,46,79,53,74,81,58,33,NaN,False,False
14,2019-04-14,90,83,89,89,66,0,53,23,64,...,48,82,57,88,91,62,34,NaN,False,False
15,2019-04-21,95,84,90,89,70,0,52,23,71,...,45,83,55,94,84,61,28,NaN,False,False
16,2019-04-28,95,83,90,100,79,0,51,26,69,...,48,82,56,88,89,61,31,NaN,False,False
17,2019-05-05,94,82,90,92,71,0,56,25,65,...,48,82,52,94,92,63,37,NaN,False,False
18,2019-05-12,90,83,87,98,69,0,57,27,70,...,49,86,48,84,93,66,53,NaN,False,False
19,2019-05-19,91,84,83,100,66,1,52,25,73,...,48,86,52,80,93,84,61,NaN,False,False