In [10]:
import requests
import json
import pandas as pd
from pytrends.request import TrendReq

pytrends = TrendReq(hl='en-US', tz=360)

In [11]:
state =[
        'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY',
        'LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND',
        'OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'
        ]

In [12]:
# getting length of list
# length = len(state)
  
# Iterating the index
# same as 'for x in range(len(list))'
for x in range(0, 50):
    api = 'https://api.covidtracking.com/v1/states/'+state[x]+'/current.json'
#     print(api)
    r = requests.get(api)
    rj = r.json()
# print("ok",rj['state'])
# jsonVal = r.text    
# print("hello",jsonVal) 
    print("Covid19 Effect by states:")
    print("State Name:",rj['state']," Positive cases:",rj['positive']," Death:",rj['death'])

Covid19 Effect by states:
State Name: AL  Positive cases: 343458  Death: 4685
Covid19 Effect by states:
State Name: AK  Positive cases: 43990  Death: 200
Covid19 Effect by states:
State Name: AZ  Positive cases: 493041  Death: 8424
Covid19 Effect by states:
State Name: AR  Positive cases: 213969  Death: 3441
Covid19 Effect by states:
State Name: CA  Positive cases: 2072665  Death: 23983
Covid19 Effect by states:
State Name: CO  Positive cases: 323619  Death: 4592
Covid19 Effect by states:
State Name: CT  Positive cases: 172743  Death: 5791
Covid19 Effect by states:
State Name: DE  Positive cases: 54473  Death: 895
Covid19 Effect by states:
State Name: FL  Positive cases: 1243118  Death: 21437
Covid19 Effect by states:
State Name: GA  Positive cases: 540758  Death: 10685
Covid19 Effect by states:
State Name: HI  Positive cases: 21323  Death: 285
Covid19 Effect by states:
State Name: ID  Positive cases: 135233  Death: 1349
Covid19 Effect by states:
State Name: IL  Positive cases: 934142  Death: 17224
Covid19 Effect by states:
State Name: IN  Positive cases: 492021  Death: 7801
Covid19 Effect by states:
State Name: IA  Positive cases: 235061  Death: 3744
Covid19 Effect by states:
State Name: KS  Positive cases: 209689  Death: 2507
Covid19 Effect by states:
State Name: KY  Positive cases: 255563  Death: 2534
Covid19 Effect by states:
State Name: LA  Positive cases: 296499  Death: 7272
Covid19 Effect by states:
State Name: ME  Positive cases: 21547  Death: 319
Covid19 Effect by states:
State Name: MD  Positive cases: 265440  Death: 5680
Covid19 Effect by states:
State Name: MA  Positive cases: 349602  Death: 12010
Covid19 Effect by states:
State Name: MI  Positive cases: 516326  Death: 12690
Covid19 Effect by states:
State Name: MN  Positive cases: 406545  Death: 5107
Covid19 Effect by states:
State Name: MS  Positive cases: 205023  Death: 4565
Covid19 Effect by states:
State Name: MO  Positive cases: 380643  Death: 5309
Covid19 Effect by states:
State Name: MT  Positive cases: 79433  Death: 919
Covid19 Effect by states:
State Name: NE  Positive cases: 161162  Death: 1558
Covid19 Effect by states:
State Name: NV  Positive cases: 215653  Death: 2944
Covid19 Effect by states:
State Name: NH  Positive cases: 39933  Death: 701
Covid19 Effect by states:
State Name: NJ  Positive cases: 458901  Death: 18613
Covid19 Effect by states:
State Name: NM  Positive cases: 137226  Death: 2316
Covid19 Effect by states:
State Name: NY  Positive cases: 914522  Death: 29396
Covid19 Effect by states:
State Name: NC  Positive cases: 513930  Death: 6526
Covid19 Effect by states:
State Name: ND  Positive cases: 91355  Death: 1271
Covid19 Effect by states:
State Name: OH  Positive cases: 664668  Death: 8476
Covid19 Effect by states:
State Name: OK  Positive cases: 276508  Death: 2357
Covid19 Effect by states:
State Name: OR  Positive cases: 108326  Death: 1422
Covid19 Effect by states:
State Name: PA  Positive cases: 605141  Death: 14883
Covid19 Effect by states:
State Name: RI  Positive cases: 82066  Death: 1704
Covid19 Effect by states:
State Name: SC  Positive cases: 288892  Death: 5124
Covid19 Effect by states:
State Name: SD  Positive cases: 96963  Death: 1446
Covid19 Effect by states:
State Name: TN  Positive cases: 560892  Death: 6443
Covid19 Effect by states:
State Name: TX  Positive cases: 1660551  Death: 26421
Covid19 Effect by states:
State Name: UT  Positive cases: 264078  Death: 1212
Covid19 Effect by states:
State Name: VT  Positive cases: 6966  Death: 121
Covid19 Effect by states:
State Name: VA  Positive cases: 329577  Death: 4840
Covid19 Effect by states:
State Name: WA  Positive cases: 233093  Death: 3184
Covid19 Effect by states:
State Name: WV  Positive cases: 80177  Death: 1253
Covid19 Effect by states:
State Name: WI  Positive cases: 506022  Death: 5029
Covid19 Effect by states:
State Name: WY  Positive cases: 43146  Death: 373

In [13]:
payload = {'key1': 'value1', 'key2': ['value2', 'value3']}
r = requests.get('https://api.covidtracking.com/v1/states/ca/info.json', params=payload)
print('URL: ', r.url)
print('HEADERS: ', r.headers)
# for STATES in r: 
print('TEXT: ', r.json)

URL:  https://api.covidtracking.com/v1/states/ca/info.json?key1=value1&key2=value2&key2=value3
HEADERS:  {'Accept-Ranges': 'bytes', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'public, max-age=0, must-revalidate', 'Content-Type': 'application/json', 'Date': 'Sun, 27 Dec 2020 19:25:29 GMT', 'Etag': '"ace746e951b03460f238093da7cb08d2-ssl-df"', 'Strict-Transport-Security': 'max-age=31536000', 'Content-Encoding': 'gzip', 'Content-Length': '1306', 'Age': '3950', 'Connection': 'keep-alive', 'Server': 'Netlify', 'Vary': 'Accept-Encoding', 'X-NF-Request-ID': '54255ef1-5aec-4884-aab9-964a1fd9593f-22821684'}
TEXT:  <bound method Response.json of <Response [200]>>

In [14]:
pytrends.trending_searches(pn='united_states')

                            0
0           Colts vs Steelers
1                 Phil Niekro
2           Falcons vs Chiefs
3             Hilaria Baldwin
4               Sylvie's Love
5      Liverpool vs West Brom
6                Timberwolves
7                     Pompeii
8              Dwayne Haskins
9         Dolphins vs Raiders
10         49ers vs Cardinals
11                 Buccaneers
12            NFL games today
13                  Ty Jordan
14                Luke Harper
15           Cleveland Browns
16                    Kwanzaa
17  Coastal Carolina Football
18              Chicago Bears
19   Rockets vs Trail Blazers

In [15]:
#cat_list = [184, 1116, 891, 1097, 1291, 1325, 655, 466, 467, 1203]

In [16]:
cat_list ={ "Celebrities & Entertainment News": 184, "Film & TV Industry": 1116, "Concerts & Music Festivals": 891,
            "Guitars": 1325, "Industrial & Product Design": 655, "Home Financing": 466,"Auto Insurance": 467,
            "Media Critics & Watchdogs": 1203}